### ISSUE TITLE
Agree on data types for logical models

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-mpd#10]
It would make sense if we agreed on data types first, and then created the models following the same data type logic. I'm not a big fan of 'untyped', current data types in the IG are not sufficient (nor sufficiently defined).

**Comment by costateixeira** [comment]
* We need to figure out how to handle "complex" abstract data types such as "address".
  * Possibly we'd need to define a structure that has sufficient details to ensure common "core" across implementations, but not too many details as to break compatibility.

**Comment by rlindstrm** [comment]
This one was questionable:
Profile: REAL
Parent: Element
Description: "RealNumber"
* . ^short = "Decimal number"
* . ^definition = "A scalar magnitude. Typically used whenever quantities are measured, estimated, or computed from other real numbers. The typical representation is decimal, where the number of significant decimal digits is known as the precision."

I agree it was my oversimplification to call real numbers decimal numbers in short description. But I don't know which way to fix it. I don't think we want to allow infinite decimals nor π or √2 under this data type? Because normally we would expect to have a decimal number with a finite and reasonable number of digits after the decimal point. Or not? I really don't know.

**Comment by costateixeira** [comment]
When would you need to say 'this element has a value which is a number but
may not be a rational number'?

**Comment by rlindstrm** [comment]
I don't get what you're suggesting. Using data type Rational Number?
I don't think we ever need to say that something cannot be a rational number. I just don't like Real Number (taken from V3), because it includes π and  √whatever, which may not be expected by default (correct me if I'm wrong), and I don't like to use Decimal, because that would allow infinite decimals, which are definately not handled.
In UNICOM IG, I left RealNumber and wrote in short "By default finite decimal". But that's not a clean solution maybe.

**Comment by costateixeira** [comment]
I mean - rather have a number. No distinction of types unless we really
need it

**Comment by rlindstrm** [comment]
I'd say integer vs decimal is pretty big difference. I would like to keep that in.

**Comment by costateixeira** [comment]
Agree

**Comment by rlindstrm** [comment]
Data types moved here: https://build.fhir.org/ig/IHE/datatypes/artifacts.html
