### ISSUE TITLE
Selection of FHIR release

### ISSUE THREAD

**Issue by juergenbrandstaetter** [IHE/pharm-mpd#14]
Decision between: R5 or R4B

**Comment by juergenbrandstaetter** [comment]
03.04.2023:
Jose: no one is really working on R4B and it's not deployed in the market widely. Changes mainly in MedicationDefinition (UNICOM) and MedicationKnowledge and they have changed a lot from R4 to R5.
Michael: depends on the parties, who have already created specifications, for example on R4B
Jürgen: Agrees to Michael in princicple, but R4B is not complete for what we need to accomplish, would not consider present developments in that special case, but go for R5
Joao: we should use the latest version for this development in principle (= R5)
Rutt: Estonia switched already to R5 in general from R4 (R4B is skipped)
Switzerland situation: currently on "document-based" FHIR. This work is affecting them in the future, so no need to especially taking care on their current FHIR release status.

**Motion: "Use FHIR R5 for this development", seconded**
**Decision: Approved**

**Comment by rlindstrm** [comment]
Decided and done. MPD and MEOW are both using R5.
