### ISSUE TITLE
Create common logical data model

### ISSUE THREAD

**Issue by costateixeira** [IHE/pharm-mpd#20]
Independent from FHIR. 
* Collect logical models from CMPD, HMW, UNICOM, eHDSI, ISO, and other relevant specifications. 
* Create and document the Prescription data model.

**Comment by costateixeira** [comment]
from the analysis in HMW (this is NOT the V2 model:
* Patient
  * Name
  * Personal Identification
  * Administrative Sex
  * Date of Birth
  * Address
  * Contact Information
  * Guardian contact information
  * Guardian Name
  * Guardian Relationship
  * Marital Status
  * Race
  * Ethnicity
  * Religious Affiliation
  * Patient Contact
  * Information
  * Payers
  * Coded Vital Signs
  * Allergies and Drug Sensitivities
  * Active Problems
  * Resolved Problems
  * Immunizations
  * Pregnancy History
* Encounter
  * EncounterID
  * Patient Location
  * Organization Name
  * Address
  * Organization Identifier
  * Contact Information
* Prescription
  * PrescriptionID
  * Prescriber
    * Name
    * Address
    * HCP Identification
    * Profession
    * Contact Information
    * Speciality
  * Prescription_Item
    * Date/Time of prescription
    * Diagnosis
    * Item ID
    * Frequency/Posology
    * Route
    * Site
    * Dose
    * Dose Units
    * Rate
    * Instructions
    * Fulfilment instructions
    * Medication
      * Code
      * Coding system
      * Name
      * Form code
      * Form coding system
      * Active Ingredients
    * Substitution allowed
  * Observations

**Comment by costateixeira** [comment]
Short version of HMW mode: 
* Patient
  * ...
* Encounter
  * ...
* Prescription
  * PrescriptionID
  * Prescriber
    * ...
  * Date/Time of prescription
  * Prescription_Item
    * Item ID
    * Diagnosis/indication
    * Frequency/Posology
    * Route
    * Site
    * Dose / Rate
    * Instructions
    * Fulfilment instructions
    * Medication
      * Code + system
      * Name
      * Dose Form 
      * Active Ingredients
    * Substitution allowed
  * Observations

**Comment by juergenbrandstaetter** [comment]
Call 24.07.2023: Based on the current status, Rutt/Triin will create a logical model draft until next call on August 21

**Comment by rlindstrm** [comment]
Prescription: http://build.fhir.org/ig/IHE/pharm-mpd/StructureDefinition-MedicationPrescription.html 
Dispensation: http://build.fhir.org/ig/IHE/pharm-mpd/StructureDefinition-MedicationDispensation.html

**Comment by joofio** [comment]
check the google docs and compare with what is done

**Comment by costateixeira** [comment]
The following data models are ready for review:
* Medication
* Dispense
* Prescription

@costateixeira will add the UML-like diagrams for easier review
The group can review.
We can consider adding a page on how to read / interpret / use logical data models
