### ISSUE TITLE
Identify needed extensions for FHIR resources so that IHE can use "consensual" extensions

### ISSUE THREAD

**Issue by costateixeira** [IHE/pharm-mpd#26]
Currently identified examples:

* Medication Classification - different countries are putting e.g. ATC in different places. This should be harmonized
* Package size - we must consider the perceived need - in prescription it may not be very much needed, but in dispensation it is important. 
* Prescribed amount ?

This should align with the eHDSI Cross-border logical model and also kept in line within JA09 and other projects.

**Comment by rlindstrm** [comment]
Started from eHN guidelines (eP+eD and PS medication summary section). Summary [here](https://docs.google.com/spreadsheets/d/1VwfUt6eDaJORHjuD4m36Fhj1_JCK4G628gScuT-b1qE/edit?usp=sharing).

**Medication**

- Name of the medicinal product
- Product classification
- Pharmaceutical dose form (possibly extension needed for dose form type or different dose forms for one product)
- Unit of presentation (if used as an independent characteristic)
- Package type (container)
- Pack size (corresponds to totalAmount, but needed on different layers to describe pack size such as "5 vials of 3ml each"

Not in eHN guidelines, but present in IHE logical model (from UNICOM, so candidates for extension):
- Administration device (reference from .item)
- Strength type (modelling not clear for the profile)
- Name type and language

**MedicationRequest**
- Quantity of prescribed products (number of packages or manufactured items of product).


Will make a comparison of national implementations for these elements and add better justification for change requests.

**Comment by rlindstrm** [comment]
Started this page in wiki: https://github.com/IHE/pharm-mpd/wiki/Extensions

**Comment by costateixeira** [comment]
**Ready for HL7 discussion:**
* Medication
** Classification
** Pack size
** Product name
* MedicationRequest
** TotalAmount

Need discussion: 
* Dose form type + multiple dose forms
* Multiple items  for 1 product including administration device
* Strength 

Some countries add prescribed product in 2 levels: while the prescription can be generic
* requestedMedicinalProduct? We could consider how to express "the prescription is on the generic code level, but the request is to dispense one specific branded / package item). If a reason would be needed for justifying a specific brand, this would call into substitution.

**Comment by rlindstrm** [comment]
Extensions are mostly done and in discussion in HL7 Pharmacy
https://github.com/IHE/pharm-mpd/wiki/Extensions
Individual topics will get a dedicated issue.
