### ISSUE TITLE
Add Logical Models from eHN

### ISSUE THREAD

**Issue by costateixeira** [IHE/pharm-mpd#3]

**Comment by rlindstrm** [comment]
Guessing what this means, the data you're looking for is here: https://health.ec.europa.eu/system/files/2022-06/ehealth_health-data_electronic-exchange_eprescriptions-guidelines_en.pdf

Revised in 2022, data set starts from page 21.

**Comment by rlindstrm** [comment]
Pay attention that the guidelines are not strict - it is a suggested approach without any cardinalities.

**Comment by rlindstrm** [comment]
The logical model for eHN exist and are being revised in Xt-EHR. Not relevant to create in IHE IG.
