### ISSUE TITLE
Reference strength / Strength substance

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-mpd#35]
eHN Guideline: 
Element: A.1.4.4.1. Strength of the active substance(s). 
Description: Presentation and/or concentration strength of the active substances. In
addition, reference strength could be provided (Article 1 of Directive
2001/83/EC).

Current model is a compromise, roughly following SNOMED CT modelling approach, and allowing to provide two substances for one strength (precise substance and strength substance, in case they're different).

Question: Is this okay? Change, remove, create Jira ticket?

**Comment by rlindstrm** [comment]
Current [model](https://build.fhir.org/ig/IHE/pharm-mpd/StructureDefinition-MedicinalProductLM.html)
![image](https://github.com/user-attachments/assets/8c17b115-0046-453e-9601-9ba14fc80bf1)

**Comment by weteringac** [comment]
All I wanted to say as a sidenote here with regards to the EHN guideline that in The Netherlands we have abandoned to make distinction between active ingredients and excipients. Our experts have stated everything does something in the body and making the distinction is not very useful and also sometimes very difficult. The model above has cardinality 0..1 for role and allows for this: in the Netherlands we would not use role. We would oppose to making that a required element, it's fine now.

**Comment by rlindstrm** [comment]
Comment from Kari Heinonen:
FWIW "drug dictionary matching" point might also touch the strength issue - should MPD attributes be as specific as possible in defining "what is compared against what" at database level. Or is the responsibility of filtering/validating "raw technical matches" left to implementations and assumptions about what kind of strength is "most often" used for a given product category.

**Comment by rlindstrm** [comment]
@costateixeira 
I'm going to need help with the details of the extension here. Would it be on ingredient or strength element? Let's discuss.

**Comment by rlindstrm** [comment]
Added it to strength for now. Seems to work and looks like this: https://build.fhir.org/ig/IHE/pharm-mpd/branches/master/Medication-01C-Cefuroxime1500Branded.json.html 

Also added strengthType to the profile, but without an appropriate valueset, it has little value. Not used in examples right now.

In the logical model we have ingredient.role as well - active ingredient, excipient - but in Medication resource it maps to a boolean isActive. Shall we do something about it?

**Comment by rlindstrm** [comment]
Should we create Jira tickets or is this not relevant enough?

**Comment by costateixeira** [comment]
we can adopt this name in IHE too
