### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-mpd#36]
Not in eHN Guidelines.

Present in IHE model.

Question: Is this okay? Change, remove, create Jira ticket?

![image](https://github.com/user-attachments/assets/aaec4b52-881f-4c56-b8b5-1f5fe7d90a64)

**Comment by weteringac** [comment]
Is the proposal to add this to Medication or to MedicationKnowledge or both?

**Comment by rlindstrm** [comment]
Decided to keep it as is in 25.07.2024 call.
Rutt will make some better examples.

**Comment by rlindstrm** [comment]
Device as a codeable concept can be added under item.concept.
In that case, we'd only need a quantity as an extension.

Or we could have a device extension under item that has concept and quantity both.

Or we could keep it on top level like it is now.

**Comment by rlindstrm** [comment]
Device should be made repeatable. Need advice. https://github.com/IHE/pharm-mpd/blob/master/input/fsh/examples/medication.fsh#L144

**Comment by rlindstrm** [comment]
Got the repeated extension working - thank you Kari for your offline advice. :)

The above question remains: is the extension in the right place or would we want it differently.

**Comment by rlindstrm** [comment]
**From Kari:**
Placement of device extension - as I understand the question, there are three possibilities:

1) as repeating one at Medication resource level (as used in current profile)
2) as a non-repeating to .ingredient (which is already 0..*; holds concept & quantity)
3) as a non-repeating to .ingredient.item (and as you noted CodeableReference could theoretically hold the coded form of device so needs only quantity as extension)
Main issue of option 2 is .item being 1..1; so what to put there for a "device ingredient" ? For option 3 it feels semantically wrong to have a code there representing something not (directly/nominally) allowed as a resource reference. Technically “device info encapsulated in a nested Med-resource” is OK (?), but in that case, there is no need for quantity extension either (as we have .totalVolume in referenced resource). Option 3 also raises the question of easily separating "devices" from other "ingredients" as we don’t have any code available for that in Medication.ingredient. Option 2 has .item and device extension as siblings (under .ingredient) which makes this separation relatively straightforward. But should you need some additional info (i.e. using characteristics key-value pair extension on Med) for specific "device ingredient" things get somewhat convoluted.

Also thinking about it further, the "quantity only" variation for option 3 has a side-effect of opening up a way to generally avoid nesting Med resources just to have a .totalVolume for that individual part of (combi-pack) product. At the cost of losing the container to hold the other bits of information normally relevant to that use case - and I see overall logical template of "what goes where in use case X" beneficial as too many "alternate ways" to represent things is bad. But then again, how far does it make sense to develop "stuff" using extensions in MPD context before a more fundamental change to base spec is put forward (see option 4. below) ?

I think option 1 strikes a balance of a) supporting the immediate MPD need for a concise list of product's devices and their quantities and b) also allows, if necessary, using recursive Medication (each representing just one device) to define additional characteristics targeting that specific "item". Or to go even further (in R5) using the actual full Definitionals.

Plus for completeness, a note must be made about the unrealistic option 4 of "simply" allowing DeviceDefinition (which might be more useful in MPD context than Device) as ingredient.item reference that might actually make the extension unnecessary.

**Comment by rlindstrm** [comment]
@costateixeira 
Is this also something to take up in HL7 Pharmacy or too specific?

**Comment by rlindstrm** [comment]
Rediscussed with Xt-EHR(Daniel), and agreed to leave device extension where it is (reasoning similar to what's been provided from Kari - see above).
