### ISSUE TITLE
MedicationDispense.receiver

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-mpd#45]
.receiver is can be recorded as a reference to one of the following: [Patient](https://build.fhir.org/patient.html) | [Practitioner](https://build.fhir.org/practitioner.html) | [RelatedPerson](https://build.fhir.org/relatedperson.html) | [Location](https://build.fhir.org/location.html) | [PractitionerRole](https://build.fhir.org/practitionerrole.html))

Estonia proposes adding "Person" in the list to avoid creating RelatedPersons with unknown relationships or partial information.

Consider HL7 Jira ticket. Find previous discussion in Zulip or HL7 Confluence @costateixeira

**Comment by costateixeira** [comment]
We can close this and implementers can use a RelatedPerson with relationshipType = unknown
